language: php

dist: xenial

sudo: false

services:
  - postgresql

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3.7
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.2
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.4
      env: DB=PGSQL CORE_RELEASE=3 INSTALL_PHPUNIT_FORK=1

before_script:
 - composer self-update || true
 - if [ $INSTALL_PHPUNIT_FORK ]; then composer require --no-update --dev sminnee/phpunit-mock-objects:^3.4.7; fi
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit framework/tests
